# vim:fileencoding=utf-8:foldmethod=marker
font_family      family="JetBrains Mono" style=ExtraLight features="+ss02 +cv03 +cv04 +cv08 +cv14 +cv15 +cv16 +cv18 +cv19 +cv20 +zero"
bold_font        family="JetBrains Mono" style=Regular features="+ss02 +cv03 +cv04 +cv08 +cv14 +cv15 +cv16 +cv18 +cv19 +cv20 +zero"
italic_font      family="JetBrainsMono Nerd Font Mono" style="ExtraLight Italic" features="+ss02 +cv03 +cv04 +cv08 +cv14 +cv15 +cv16 +cv18 +cv19 +cv20 +zero"
bold_italic_font family="JetBrainsMono Nerd Font Mono" style=Italic features="+ss02 +cv03 +cv04 +cv08 +cv14 +cv15 +cv16 +cv18 +cv19 +cv20 +zero"
font_size 12.5

modify_font cell_width 100%
modify_font cell_height 110%

cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.0
cursor_blink_interval 0
cursor_trail 24
cursor_trail_decay 0.08 0.28
cursor_trail_start_threshold 2
cursor_trail_color none

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'call cursor(CURSOR_LINE, CURSOR_COLUMN)' -
scrollback_pager_history_size 128
pixel_scroll yes

mouse_hide_wait -1

detect_urls yes
show_hyperlink_targets cmd
paste_actions quote-urls-at-prompt,confirm
pointer_shape_when_grabbed beam

mouse_map shift+left click grabbed,ungrabbed mouse_handle_click selection link prompt

remember_window_size  yes
remember_window_position yes
enabled_layouts splits:split_axis=horizontal,stack,tall:bias=62;full_size=1
window_border_width 0.5pt
draw_minimal_borders yes

window_padding_width 3 3 0 3
inactive_text_alpha -0.92

confirm_os_window_close 1

tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 0.5 0.0
tab_bar_style custom
tab_bar_align left
tab_bar_show_new_tab_button no
tab_bar_min_tabs 2
tab_separator "  "
tab_powerline_style round
tab_title_max_length 20
tab_title_template "{title}"

active_tab_title_template "{title}"
active_tab_foreground   #89b4fa
active_tab_background   #020202
active_tab_font_style   bold
inactive_tab_foreground #bac2de
inactive_tab_background #020202
inactive_tab_font_style normal

tab_bar_background none

foreground #c2c2c2
background #020202
background_opacity 0.75
dynamic_background_opacity yes
background_blur 55

clipboard_control write-clipboard write-primary

allow_hyperlinks yes
shell_integration no-title
notify_on_cmd_finish always

macos_titlebar_color background
macos_option_as_alt both
macos_quit_when_last_window_closed yes
macos_thicken_font 0.35
:qa
macos_show_window_title_in none

action_alias launch_tab launch --type=tab --cwd=current --location=neighbor
action_alias split_right launch --location=vsplit --cwd=current
action_alias split_down launch --location=hsplit --cwd=current

map --allow-fallback=shifted,ascii cmd+f search_scrollback
map --allow-fallback=shifted,ascii cmd+d split_right
map --allow-fallback=shifted,ascii shift+cmd+d split_down

map cmd+1       goto_tab 1
map cmd+2       goto_tab 2
map cmd+3       goto_tab 3
map cmd+4       goto_tab 4
map cmd+5       goto_tab 5
map cmd+6       goto_tab 6
map cmd+7       goto_tab 7
map cmd+8       goto_tab 8
map cmd+9       goto_tab 9
map shift+cmd+]     next_tab
map shift+cmd+[    previous_tab

map --allow-fallback=shifted,ascii cmd+t launch_tab

map cmd+backspace send_text normal,application \x15
map cmd+k send_text normal,application \x1bk
map opt+left  send_text normal,application \x1bb
map opt+right send_text normal,application \x1bf
map cmd+left  send_key home
map cmd+right send_key end

include ${HOME}/.config/dotfiles-theme/kitty.conf
