set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
run-shell ~/.tmux/plugins/catppuccin/catppuccin.tmux
set -g status-style "fg=#4c4f69,bg=#e6e9ef"
set -g status-left '#{?client_prefix,#[fg=#eff1f5,bg=#df8e1d,bold] 󰘳 PREFIX #[default],}#{?window_active,#{?synchronize-panes,#[fg=#eff1f5,bg=#fe640b,bold] 󰓦 SYNC #[default],},}#{?session_many_attached,#[fg=#eff1f5,bg=#40a02b,bold] 󰖩 PAIR #[default],}#[fg=#8839ef,bg=#e6e9ef,bold] 󰆍 #S #[default]'
set -g status-right "#[fg=#4c4f69]%H:%M#[fg=#acb0be] | #[default]#(/Users/sahilsasane/dotfiles/tmux/scripts/git-branch.sh '#{pane_current_path}') #(/Users/sahilsasane/dotfiles/tmux/scripts/battery.sh) #[fg=#acb0be]| #[default]#(/Users/sahilsasane/dotfiles/tmux/scripts/memory-pressure.sh)#[fg=#acb0be] | #[default]#(/Users/sahilsasane/dotfiles/tmux/scripts/app-icon.sh '#{pane_current_command}') "
set -g window-status-style "fg=#6c6f85,bg=#e6e9ef"
set -g window-status-current-style "fg=#8839ef,bg=#e6e9ef,bold"
set -g window-status-format "#[fg=#6c6f85,bg=#e6e9ef] #I #W "
set -g window-status-current-format "#[fg=#6c6f85,bg=#e6e9ef] #I#[fg=#8839ef,bg=#e6e9ef,bold] #W "
set -g message-style "fg=#4c4f69,bg=#eff1f5"
set -g message-command-style "fg=#4c4f69,bg=#eff1f5"
set -g mode-style "fg=#eff1f5,bg=#df8e1d"
set -g display-panes-active-colour "#1e66f5"
set -g display-panes-colour "#9ca0b0"
set -g pane-border-style fg=#acb0be
set -g pane-active-border-style fg=#1e66f5
