dialect = "uk"
timezone = "local"

search_mode = "fuzzy"
filter_mode = "global"

style = "compact"
inline_height = 10
show_preview = true
max_preview_height = 6
show_help = false
show_tabs = false

enter_accept = true
exit_mode = "return-original"
keymap_mode = "auto"

auto_sync = true
sync_frequency = "3h"

cwd_filter = ["/private/", "/secrets/"]

[search]
filters = ["directory", "session", "host", "global"]

[ui]
columns = ["duration", "time", { type = "directory", width = 25 }, "command"]

[stats]
common_subcommands = ["git", "docker", "kubectl", "npm", "pnpm", "cargo", "uv"]
common_prefix = ["sudo"]
ignored_commands = ["cd", "ls", "ll", "pwd"]

[theme]
name = "sahil-slate"
