foreground #4c4f69
background #eff1f5
background_opacity 1.0
background_blur 0
selection_foreground #4c4f69
selection_background #bcc0cc
cursor #dc8a78
cursor_text_color #eff1f5
color0 #5c5f77
color1 #d20f39
color2 #40a02b
color3 #df8e1d
color4 #1e66f5
color5 #8839ef
color6 #179299
color7 #acb0be
color8 #6c6f85
color9 #d20f39
color10 #40a02b
color11 #df8e1d
color12 #1e66f5
color13 #8839ef
color14 #179299
color15 #4c4f69
active_tab_foreground #4c4f69
active_tab_background #dce0e8
inactive_tab_foreground #6c6f85
inactive_tab_background #e6e9ef
