alias v='source .venv/bin/activate'
alias vd='deactivate 2>/dev/null || true'
alias size='du -sh -- *(DN) 2>/dev/null | sort -rh'
alias c='clear'
alias h='history'
alias j='jobs -l'
alias path='echo $PATH | tr ":" "\n"'
alias rl='source ~/.zprofile && source ~/.zshrc && exec zsh'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -pv'
alias ports='lsof -i -P -n | grep LISTEN'
alias cd='z'
alias lg='lazygit'
alias lzd='lazydocker'
alias tk='tmux kill-session -t'
alias t='tmux attach -t'
alias k='kubectl'
alias rg='rg --color=always'
alias f='fzf --preview="bat --color=always {}"'
alias vim='nvim'
alias gal='git add --all'
alias ff='fastfetch'

alias -s md='bat'
alias -s yaml='bat'
alias -s yml='bat'
alias -s py='nvim'
alias -s json='jless'
alias -s txt='bat --color=always'

alias -g NE='2>/dev/null'
alias -g C='| pbcopy'
alias -g JQ='| jq'
alias -g F='| fzf'
alias -g R='| rg'
alias -g L='| less -R'
